import React, { useState } from 'react';
import { View, Text, StyleSheet, Alert, TouchableOpacity, ScrollView } from 'react-native';
import RNPickerSelect from 'react-native-picker-select';
import { Ionicons } from '@expo/vector-icons';
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from 'react-native-responsive-screen';
import InputField from '@/components/InputField';
import Button from '@/components/Button';
import { StatusBar } from 'expo-status-bar';

import In from '@/components/DoubleSidedInput';

interface Student {
  name: string;
  email: string;
  department: string;
  batch: string;
  password: string;
}

const AdminRegisterStudent: React.FC = () => {
  const [name, setName] = useState<string>('');
  const [email, setEmail] = useState<string>('');
  const [department, setDepartment] = useState<string>('');
  const [batch, setBatch] = useState<string>('');
  const [password, setPassword] = useState<string>('');
  const [departmentSelected, setDepartmentSelected] = useState<boolean>(false);

  const generatePassword = () => {
    const autoGeneratedPassword = Math.random().toString(36).slice(-8);
    setPassword(autoGeneratedPassword);
    };

  const registerStudent = () => {
    if (!name || !email || !batch || !password || !department) {
      Alert.alert('Error', 'Please fill in all fields.');
      return;
    }

    const newStudent: Student = {
      name,
      email,
      department,
      batch,
      password,
    };

    console.log('Student registered:', newStudent);
    Alert.alert('Success', `Student registered successfully with password: ${password}`);
    setName('');
    setEmail('');
    setDepartment('');
    setBatch('');
    setPassword('');
    setDepartmentSelected(false);
  };

  return (
    <>
    <StatusBar style='dark' backgroundColor='white'/>
     <ScrollView contentContainerStyle={styles.container}>
      <Text style={styles.title}>Register New Student</Text>
      
      <InputField
        icon="person"
        placeholder="Name"
        value={name}
        onChangeText={setName}
      />
      <InputField
        icon="mail"
        placeholder="Email"
        value={email}
        onChangeText={setEmail}
        keyboardType="email-address"
      />
      <InputField
        icon="school"
        placeholder="Batch"
        value={batch}
        onChangeText={setBatch}
      />
     <In
        placeholder="Set password"
        icon="lock-closed"
        rightIcon={
          <TouchableOpacity onPress={generatePassword}>
            <Ionicons name="reload" size={24} color="black" />
          </TouchableOpacity>
        }
        onChangeText={setPassword}
        value={password}
      />
      <View style={styles.pickerWrapper}>
        <Ionicons name="business" size={24} color="black" style={styles.pickerIcon} />
        <View style={styles.pickerContainer}>
          <RNPickerSelect
            onValueChange={(value) => {
              setDepartment(value);
              setDepartmentSelected(true);
            }}
            items={[
              
              { label: 'Computer', value: 'Computer' },
              { label: 'Civil', value: 'Civil' },
              { label: 'Electronics', value: 'Electronics' },
              { label: 'BCA', value: 'BCA' },
              { label: 'IT', value: 'IT' },
              { label: 'Software', value: 'Software' },
            ]}
            style={{
              placeholder: {
                color: '#999',
                fontFamily: 'Nunito-SemiBold',
                fontSize: 16,
              },
            }}
            placeholder={{
              label: 'Choose Department',
              value: '',
            }}
          />
        </View>
      </View>
      <TouchableOpacity onPress={registerStudent}>
        <Button title="Add new student" />
      </TouchableOpacity>
    </ScrollView>
    </>
  );
};

const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    padding: 20,
    backgroundColor: '#E2E2E2',
    alignItems: 'center',
    gap: hp('4%'),
    paddingTop: 20
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 20,
    color: '#333',
    fontFamily: 'Nunito-ExtraBold',
  },
  pickerWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderColor: '#1A162B',
    borderWidth: 1,
    borderRadius: 10,
    backgroundColor: '#E2E2E2',
    paddingLeft: 10,
    height: hp('6%'),
    width: wp('90%'),
  },
  pickerIcon: {
    marginRight: 10,
  },
  pickerContainer: {
    flex: 1,
  },
});

export default AdminRegisterStudent;
